apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      volumes:
      - name: dir
        hostPath:
          path: /src
      imagePullSecrets:
      - name: my-key
      containers:
      - name: app2
        image: registry.hub.docker.com/jahirshawon/app2
        imagePullPolicy: Always
        volumeMounts:
        - name: dir
          mountPath: /src
        ports:
          - containerPort: 8000
      nodeSelector:
        region: "worker2"
